"""Durable bridge jobs. A restart records interruption; it never repeats work."""
import datetime
from contextlib import contextmanager
import json
import os
from pathlib import Path
import re
import sqlite3
import tempfile
import threading
import time
import uuid


class BusyError(Exception):
    pass


class JobStore:
    def __init__(self, path, vault, max_active=2, titler=None):
        self.path = path
        self.vault = Path(vault)
        self.max_active = max_active
        # titler(job) -> {"title": ..., "tags": [...]} or None; MiniMax names and
        # tags reports in production, tests and offline runs get the dated template.
        self.titler = titler
        self.lock = threading.RLock()
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with self.connect() as db:
            db.execute("CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, started INTEGER, payload TEXT)")

    @contextmanager
    def connect(self):
        db = sqlite3.connect(self.path, timeout=10)
        try:
            with db:
                yield db
        finally:
            db.close()

    def save(self, job):
        with self.lock, self.connect() as db:
            db.execute("INSERT OR REPLACE INTO jobs VALUES (?, ?, ?)",
                       (job["id"], job["started"], json.dumps(job)))

    def get(self, jid):
        with self.connect() as db:
            row = db.execute("SELECT payload FROM jobs WHERE id = ?", (jid,)).fetchone()
        return json.loads(row[0]) if row else None

    def recent(self, limit=50):
        with self.connect() as db:
            rows = db.execute("SELECT payload FROM jobs ORDER BY started DESC, rowid DESC LIMIT ?",
                              (min(max(limit, 1), 100),)).fetchall()
        return [json.loads(row[0]) for row in rows]

    def create(self, text, agent, route):
        with self.lock, self.connect() as db:
            # Admission and insertion share a transaction, including across processes.
            db.execute("BEGIN IMMEDIATE")
            active = db.execute("SELECT count(*) FROM jobs WHERE json_extract(payload, '$.status') = 'running'").fetchone()[0]
            if active >= self.max_active:
                raise BusyError("All agent slots are busy. Retry when a running job finishes.")
            job = {"id": uuid.uuid4().hex, "agent": agent, "text": text,
                   "status": "running", "started": int(time.time()), "answer": "", "route": route}
            db.execute("INSERT INTO jobs VALUES (?, ?, ?)", (job["id"], job["started"], json.dumps(job)))
        return job

    def file_report(self, job):
        # Reports are generated by the bridge, not left to an agent's best effort.
        # Refuse symlink directories so a vault note cannot redirect these writes.
        root = self.vault.resolve(strict=True)
        directory = root
        for part in ("Resources", "Reports"):
            directory = directory / part
            if directory.is_symlink():
                raise OSError("report directory must not be a symlink")
            directory.mkdir(exist_ok=True)
        stamp = datetime.datetime.fromtimestamp(job["started"], datetime.timezone.utc).strftime("%Y-%m-%d")
        title, tags = "", []
        if self.titler:
            try:
                meta = self.titler(job) or {}
                candidate = str(meta.get("title") or "").strip()
                if candidate and len(candidate.encode()) <= 160 and not re.search(r'[\x00-\x1f\x7f/\\\[\]#|:]', candidate):
                    title = candidate
                tags = [t for t in (str(t).strip().lower() for t in (meta.get("tags") or []))
                        if re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,39}", t)][:4]
            except Exception:
                title, tags = "", []
        heading = title or f"Agent report {stamp} {job['id']}"
        name = f"{heading} ({job['id'][:8]}).md" if title else f"{heading}.md"
        path = directory / name
        route = job.get("route", {})
        content = (f"---\ntype: report\nstatus: {job['status']}\ntags: [{', '.join(tags or ['agents', 'report'])}]\n"
                   f"created: {stamp}\nagent: muninn-bridge\njob: {job['id']}\n---\n\n"
                   f"# {heading}\n\nUp: [[Agents MOC]]\n\n"
                   f"- Worker: {job['agent']}\n- Router: {route.get('via', 'unknown')}\n"
                   f"- Status: {job['status']}\n- Started (Unix): {job['started']}\n"
                   f"- Ended (Unix): {job.get('ended', '')}\n\n"
                   f"## Request\n\n{job['text']}\n\n## Result\n\n{job['answer']}\n\n"
                   f"## Routing decision\n\n```json\n{json.dumps(route, indent=2, ensure_ascii=False)}\n```\n")
        fd, tmp = tempfile.mkstemp(dir=directory, prefix=".report-", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(tmp, 0o664)
            os.replace(tmp, path)
        finally:
            if os.path.exists(tmp):
                os.unlink(tmp)
        return str(path.relative_to(root))

    def finish(self, job):
        job["ended"] = int(time.time())
        # Persist executor output before NFS I/O, so even a crash while filing
        # cannot lose the result or falsely advertise a filed report.
        result_status = job["status"]
        job.update(status="running", result_status=result_status, filing=True)
        self.save(job)
        self._file_terminal(job)

    def _file_terminal(self, job):
        job["status"] = job.pop("result_status", "failed")
        job.pop("filing", None)
        try:
            job["report"] = self.file_report(job)
        except Exception as exc:
            job["report_error"] = str(exc)[:300]
            job["status"] = "failed"
            job["answer"] += "\n\nReport filing failed; the result is retained in job history."
        self.save(job)

    def recover(self):
        with self.connect() as db:
            pending = [json.loads(row[0]) for row in db.execute(
                "SELECT payload FROM jobs WHERE json_extract(payload, '$.status') = 'running'")]
        for job in pending:
            if job.get("filing"):
                self._file_terminal(job)
            else:
                job.update(status="failed", answer="Bridge restarted before completion. Work may have partially executed; inspect before retrying.")
                self.finish(job)
